version: "3.0"
 
services:
  web:
    image: informer_app
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --timeout 200
    volumes:
      - .:/informer_app
      - static:/staticfiles/
      - media:/mediafiles/
    expose:
      - 8000
    env_file:
    - ./.dev.env
    depends_on:
      - db
  db:
    image: postgres:14.7-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./.db.env
    ports:
     - "5432:5432"
  nginx:
    build: ./nginx
    volumes:
      - static:/staticfiles/
      - media:/mediafiles/
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres:
  static:
  media: