version: "3.0"
 
services:
  web:
    image: informer_app
    build: .
    command: gunicorn Ukraine_web_informer.wsgi:application --bind 0.0.0.0:8000 --timeout 200
    volumes:
      - .:/informer_app
      - static:/staticfiles/
    expose:
      - 8000
    env_file:
    - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env.db.dev
    ports:
     - "5432:5432"
  nginx:
    build: ./nginx
    volumes:
      - static:/staticfiles/
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres:
  static: