# Generated by Django 4.1.2 on 2022-10-19 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sended_to',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.messages', unique=True),
        ),
    ]
