# Generated by Django 4.1.2 on 2022-10-21 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_sended_to_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replies',
            name='topic',
        ),
        migrations.AlterField(
            model_name='sended_to',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.replies', unique=True),
        ),
    ]
