# Generated by Django 4.1.2 on 2022-10-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Category's name")),
                ('description', models.CharField(max_length=600, null=True, verbose_name="Category's description")),
            ],
        ),
    ]
